; ===========================================================================
; ║                                                                         ║
; ║                             SONIC&K SOUND DRIVER                        ║
; ║                         Modified SMPS Z80 Type 2 DAC                    ║
; ║                                                                         ║
; ===========================================================================
; Disassembled by MarkeyJester
; Routines, pointers and stuff by Linncaki
; Thoroughly commented and improved (including optional bugfixes) by Flamewing
; ===========================================================================
; Permission to use, copy, modify, and/or distribute this software for any
; purpose with or without fee is hereby granted.
;
; THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
; WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
; MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
; ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
; WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
; ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT
; OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
; ===========================================================================
; Sound Bank
; ===========================================================================
SndBank:			startBank

; ===========================================================================
; SFX Pointers
; ===========================================================================
		Snd_Master_Table
; ---------------------------------------------------------------------------
SEGA_PCM:	binclude "Sound/Sega PCM.pcm"
SEGA_PCM_End
		even

; Normal
Sound_RingRight:			include "Sound/SFX/33.asm"
Sound_RingLeft:				include "Sound/SFX/34.asm"
Sound_Death:				include "Sound/SFX/35.asm"
Sound_Skid:				include "Sound/SFX/36.asm"
Sound_SpikeHit:				include "Sound/SFX/37.asm"
Sound_Bubble:				include "Sound/SFX/38.asm"
Sound_Splash:				include "Sound/SFX/39.asm"
Sound_Shield:				include "Sound/SFX/3A.asm"
Sound_Drown:				include "Sound/SFX/3B.asm"
Sound_Roll:				include "Sound/SFX/3C.asm"
Sound_Break:				include "Sound/SFX/3D.asm"
Sound_FireShield:			include "Sound/SFX/3E.asm"
Sound_BubbleShield:			include "Sound/SFX/3F.asm"
Sound_UnknownShield:			include "Sound/SFX/40.asm"
Sound_LightningShield:			include "Sound/SFX/41.asm"
Sound_InstaAttack:			include "Sound/SFX/42.asm"
Sound_FireAttack:			include "Sound/SFX/43.asm"
Sound_BubbleAttack:			include "Sound/SFX/44.asm"
Sound_ElectricAttack:			include "Sound/SFX/45.asm"
Sound_Whistle:				include "Sound/SFX/46.asm"
Sound_SandwallRise:			include "Sound/SFX/47.asm"
Sound_Blast:				include "Sound/SFX/48.asm"
Sound_Thump:				include "Sound/SFX/49.asm"
Sound_Grab:				include "Sound/SFX/4A.asm"
Sound_WaterfallSplash:			include "Sound/SFX/4B.asm"
Sound_GlideLand:			include "Sound/SFX/4C.asm"
Sound_Projectile:			include "Sound/SFX/4D.asm"
Sound_MissileExplode:			include "Sound/SFX/4E.asm"
Sound_FlamethrowerQuiet:		include "Sound/SFX/4F.asm"
Sound_BossActivate:			include "Sound/SFX/50.asm"
Sound_MissileThrow:			include "Sound/SFX/51.asm"
Sound_SpikeMove:			include "Sound/SFX/52.asm"
Sound_Charging:				include "Sound/SFX/53.asm"
Sound_BossLaser:			include "Sound/SFX/54.asm"
Sound_BlockConveyor:			include "Sound/SFX/55.asm"
Sound_FlipBridge:			include "Sound/SFX/56.asm"
Sound_Geyser:				include "Sound/SFX/57.asm"
Sound_FanLatch:				include "Sound/SFX/58.asm"
Sound_Collapse:				include "Sound/SFX/59.asm"
Sound_UnknownCharge:			include "Sound/SFX/5A.asm"
Sound_Switch:				include "Sound/SFX/5B.asm"
Sound_MechaSpark:			include "Sound/SFX/5C.asm"
Sound_FloorThump:			include "Sound/SFX/5D.asm"
Sound_Laser:				include "Sound/SFX/5E.asm"
Sound_Crash:				include "Sound/SFX/5F.asm"
Sound_BossZoom:				include "Sound/SFX/60.asm"
Sound_BossHitFloor:			include "Sound/SFX/61.asm"
Sound_Jump:				include "Sound/SFX/62.asm"
Sound_Starpost:				include "Sound/SFX/63.asm"
Sound_PulleyGrab:			include "Sound/SFX/64.asm"
Sound_BlueSphere:			include "Sound/SFX/65.asm"
Sound_AllSpheres:			include "Sound/SFX/66.asm"
Sound_LevelProjectile:			include "Sound/SFX/67.asm"
Sound_Perfect:				include "Sound/SFX/68.asm"
Sound_PushBlock:			include "Sound/SFX/69.asm"
Sound_Goal:				include "Sound/SFX/6A.asm"
Sound_ActionBlock:			include "Sound/SFX/6B.asm"
Sound_Splash2:				include "Sound/SFX/6C.asm"
Sound_UnknownShift:			include "Sound/SFX/6D.asm"
Sound_BossHit:				include "Sound/SFX/6E.asm"
Sound_Rumble2:				include "Sound/SFX/6F.asm"
Sound_LavaBall:				include "Sound/SFX/70.asm"
Sound_Shield2:				include "Sound/SFX/71.asm"
Sound_Hoverpad:				include "Sound/SFX/72.asm"
Sound_Transporter:			include "Sound/SFX/73.asm"
Sound_TunnelBooster:			include "Sound/SFX/74.asm"
Sound_BalloonPlatform:			include "Sound/SFX/75.asm"
Sound_TrapDoor:				include "Sound/SFX/76.asm"
Sound_Balloon:				include "Sound/SFX/77.asm"
Sound_GravityMachine:			include "Sound/SFX/78.asm"
Sound_Lightning:			include "Sound/SFX/79.asm"
Sound_BossMagma:				include "Sound/SFX/7A.asm"
Sound_SmallBumpers:			include "Sound/SFX/7B.asm"
Sound_ChainTension:			include "Sound/SFX/7C.asm"
Sound_UnknownPump:			include "Sound/SFX/7D.asm"
Sound_GroundSlide:			include "Sound/SFX/7E.asm"
Sound_FrostPuff:			include "Sound/SFX/7F.asm"
Sound_IceSpikes:			include "Sound/SFX/80.asm"
Sound_TubeLauncher:			include "Sound/SFX/81.asm"
Sound_SandSplash:			include "Sound/SFX/82.asm"
Sound_BridgeCollapse:			include "Sound/SFX/83.asm"
Sound_UnknownPowerUp:			include "Sound/SFX/84.asm"
Sound_UnknownPowerDown:			include "Sound/SFX/85.asm"
Sound_Alarm:				include "Sound/SFX/86.asm"
Sound_MushroomBounce:			include "Sound/SFX/87.asm"
Sound_PulleyMove:			include "Sound/SFX/88.asm"
Sound_WeatherMachine:			include "Sound/SFX/89.asm"
Sound_Bouncy:				include "Sound/SFX/8A.asm"
Sound_ChopTree:				include "Sound/SFX/8B.asm"
Sound_ChopStuck:			include "Sound/SFX/8C.asm"
Sound_UnknownFlutter:			include "Sound/SFX/8D.asm"
Sound_UnknownRevving:			include "Sound/SFX/8E.asm"
Sound_DoorOpen:				include "Sound/SFX/8F.asm"
Sound_DoorMove:				include "Sound/SFX/90.asm"
Sound_DoorClose:			include "Sound/SFX/91.asm"
Sound_GhostAppear:			include "Sound/SFX/92.asm"
Sound_BossRecovery:			include "Sound/SFX/93.asm"
Sound_ChainTick:			include "Sound/SFX/94.asm"
Sound_BossHand:				include "Sound/SFX/95.asm"
Sound_MechaLand:			include "Sound/SFX/96.asm"
Sound_EnemyBreath:			include "Sound/SFX/97.asm"
Sound_BossProjectile:			include "Sound/SFX/98.asm"
Sound_UnknownPlink:			include "Sound/SFX/99.asm"
Sound_SpringLatch:			include "Sound/SFX/9A.asm"
Sound_ThumpBoss:			include "Sound/SFX/9B (Sonic & Knuckles).asm"
Sound_SuperEmerald:			include "Sound/SFX/9C.asm"
Sound_Targeting:			include "Sound/SFX/9D.asm"
Sound_Clank:				include "Sound/SFX/9E.asm"
Sound_SuperTransform:			include "Sound/SFX/9F.asm"
Sound_MissileShoot:			include "Sound/SFX/A0.asm"
Sound_UnknownOminous:			include "Sound/SFX/A1.asm"
Sound_FloorLauncher:			include "Sound/SFX/A2.asm"
Sound_GravityLift:			include "Sound/SFX/A3.asm"
Sound_MechaTransform:			include "Sound/SFX/A4.asm"
Sound_UnknownRise:			include "Sound/SFX/A5.asm"
Sound_LaunchGrab:			include "Sound/SFX/A6.asm"
Sound_LaunchReady:			include "Sound/SFX/A7.asm"
Sound_EnergyZap:			include "Sound/SFX/A8.asm"
Sound_AirDing:				include "Sound/SFX/A9.asm"
Sound_Bumper:				include "Sound/SFX/AA.asm"
Sound_Spindash:				include "Sound/SFX/AB.asm"
Sound_Continue:				include "Sound/SFX/AC.asm"
Sound_LaunchGo:				include "Sound/SFX/AD (Sonic & Knuckles).asm"
Sound_Flipper:				include "Sound/SFX/AE.asm"
Sound_EnterSS:				include "Sound/SFX/AF.asm"
Sound_Register:				include "Sound/SFX/B0.asm"
Sound_Spring:				include "Sound/SFX/B1.asm"
Sound_Error:				include "Sound/SFX/B2.asm"
Sound_BigRing:				include "Sound/SFX/B3.asm"
Sound_Explode:				include "Sound/SFX/B4.asm"
Sound_Diamonds:				include "Sound/SFX/B5.asm"
Sound_Dash:				include "Sound/SFX/B6.asm"
Sound_SlotMachine:			include "Sound/SFX/B7.asm"
Sound_Signpost:				include "Sound/SFX/B8.asm"
Sound_RingLoss:				include "Sound/SFX/B9.asm"
Sound_Flying:				include "Sound/SFX/BA.asm"
Sound_FlyTired:				include "Sound/SFX/BB.asm"

; Continuous
Sound_SlideSkidLoud:		include "Sound/SFX/Continuous/BC.asm"
Sound_LargeShip:		include "Sound/SFX/Continuous/BD.asm"
Sound_RobotnikSiren:		include "Sound/SFX/Continuous/BE.asm"
Sound_BossRotate:		include "Sound/SFX/Continuous/BF.asm"
Sound_FanBig:			include "Sound/SFX/Continuous/C0.asm"
Sound_FanSmall:			include "Sound/SFX/Continuous/C1.asm"
Sound_FlamethrowerLoud:		include "Sound/SFX/Continuous/C2.asm"
Sound_GravityTunnel:		include "Sound/SFX/Continuous/C3.asm"
Sound_BossPanic:		include "Sound/SFX/Continuous/C4.asm"
Sound_UnknownSpin:		include "Sound/SFX/Continuous/C5.asm"
Sound_WaveHover:		include "Sound/SFX/Continuous/C6.asm"
Sound_CannonTurn:		include "Sound/SFX/Continuous/C7.asm"
Sound_SlideSkidQuiet:		include "Sound/SFX/Continuous/C8.asm"
Sound_SpikeBalls:		include "Sound/SFX/Continuous/C9.asm"
Sound_LightTunnel:		include "Sound/SFX/Continuous/CA.asm"
Sound_Rumble:			include "Sound/SFX/Continuous/CB.asm"
Sound_BigRumble:		include "Sound/SFX/Continuous/CC.asm"
Sound_DeathEggRiseLoud:		include "Sound/SFX/Continuous/CD.asm"
Sound_WindQuiet:		include "Sound/SFX/Continuous/CE.asm"
Sound_WindLoud:			include "Sound/SFX/Continuous/CF.asm"
Sound_Rising:			include "Sound/SFX/Continuous/D0.asm"
Sound_UnknownFlutter2:		include "Sound/SFX/Continuous/D1.asm"
Sound_GumballTab:		include "Sound/SFX/Continuous/D2.asm"
Sound_DeathEggRiseQuiet:	include "Sound/SFX/Continuous/D3.asm"
Sound_TurbineHum:		include "Sound/SFX/Continuous/D4.asm"
Sound_LavaFall:			include "Sound/SFX/Continuous/D5.asm"
Sound_UnknownZap:		include "Sound/SFX/Continuous/D6.asm"
Sound_ConveyorPlatform:		include "Sound/SFX/Continuous/D7.asm"
Sound_UnknownSaw:		include "Sound/SFX/Continuous/D8.asm"
Sound_MagneticSpike:		include "Sound/SFX/Continuous/D9.asm"
Sound_LeafBlower:		include "Sound/SFX/Continuous/DA.asm"
Sound_WaterSkid:		include "Sound/SFX/Continuous/DB.asm"

	finishBank
; ---------------------------------------------------------------------------
